### ISSUE TITLE
Error whenever I open the site.

### ISSUE THREAD

**Issue by XCE0** [discuitnet/discuit#13]
Whenever I go to discuit an error got triggered and I am left with the following massege:

Something went wrong
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Try reloading page

**Comment by TylerCode** [comment]
What browser and device are you running on?

**Comment by XCE0** [comment]
Device: linux laptop.
Browser: ungoogled chromium flatpak

**Comment by TylerCode** [comment]
I've spent some time trying to reproduce or get some detailed output but try as I might I can't get it to break. This goes for discuit.net and the dev instance I have setup. 

OS: KDE Neon (using Wayland)
Browser: Ungoogled Chromium Flatpak

Maybe someone else will have better luck?

**Comment by previnder** [comment]
I'm assuming, @XCE0, you're not talking about the discuit.net instance, since that's working fine. My guess would be that something's up with your `config.yaml` file. What does it look like?

**Comment by XCE0** [comment]
![Screenshot_20240112_015000](https://github.com/discuitnet/discuit/assets/143923725/5644c085-8620-4ff6-97d1-bb77f3a934f0)

**Comment by XCE0** [comment]
More details:

OS: Opensuse Microos,KDE.
Addons installed: ublock origin lite

**Comment by XCE0** [comment]
it seems that it get triggered when I scroll after opening the site,not randomly.

**Comment by XCE0** [comment]
I am not a developer, does the masseges in the browser console could benefit you in finding the bug?

if that is the case tell me and I will copy and paste it here.

**Comment by previnder** [comment]
Oh, this is extremely weird. I've never seen this error before, and I have no idea how to reproduce it. 

> I am not a developer, does the masseges in the browser console could benefit you in finding the bug?

The error logs in the browser console certainly could help, thanks. Maybe the addon is messing something up? Could you check if the site works in an incognito window?

**Comment by XCE0** [comment]
The same error happens in the  incognito window.

This is the error massages in the browser console :

> The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.

> Uncaught (in promise) DOMException: The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.

> Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
>     at oc (app.b15ae39ad7d85c2435b8.js:2:176116)
>     at nl (app.b15ae39ad7d85c2435b8.js:2:141111)
>     at Object.e [as onStateChange] (app.b15ae39ad7d85c2435b8.js:2:259690)
>     at Object.o [as callback] (app.b15ae39ad7d85c2435b8.js:2:257172)
>     at app.b15ae39ad7d85c2435b8.js:2:257367
>     at dc (app.b15ae39ad7d85c2435b8.js:2:179434)
>     at Object.notify (app.b15ae39ad7d85c2435b8.js:2:257336)
>     at Object.notifyNestedSubs (app.b15ae39ad7d85c2435b8.js:2:257749)
>     at o (app.b15ae39ad7d85c2435b8.js:2:257172)
>     at g (app.b15ae39ad7d85c2435b8.js:2:230755)
> fl @ app.b15ae39ad7d85c2435b8.js:2

**Comment by XCE0** [comment]
Opensuse Microos

**Comment by TylerCode** [comment]
> Opensuse Microos

Any chance you're running on ARM or another architecture? I only ask because it works fine on OpenSUSE MicroOS (KDE, which is in alpha support) and I could not get it to break. I did my best to recreate what you've mentioned here but I've had no luck. I'm using the Ungoogled Chromium Flatpak. 

Screenshot of it working:
![image](https://github.com/discuitnet/discuit/assets/18288340/bb3a6dc9-c79c-4f7c-896f-f684f34a026b)

System information:
![image](https://github.com/discuitnet/discuit/assets/18288340/bd6f4924-c072-4f28-8a33-8c118fae96b6)

**Comment by previnder** [comment]
This gets weirder and weirder. 

@XCE0, did you notice any other sites breaking in a similar way?

**Comment by XCE0** [comment]
As far as I can tell no.

**Comment by XCE0** [comment]
by the way I am not running arm

**Comment by TylerCode** [comment]
I agree, this is very strange.  I think I saw that Firefox was also included on the OS, does that work? (Waterfox would also work if you prefer not to install/use Firefox.)

I would just be curious if it works at all.
